name: Build newest deb package for aarch64 debian

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    container:
      image: debian:trixie

    steps:
      - name: Get INDI Sources
        uses: actions/checkout@v3

      - name: Build Indi Debian Package
        run: bash indi.sh

      - name: Check Build Output
        run: ls /tmp/output/*indi*

      - name: Build Indi ZWO ASI Driver Debian Packages
        run: bash indi-3rdparty.sh

      - name: Check Build Output (ZWO ASI)
        run: ls /tmp/output/*asi*

      - name: Build Openphd2 Debian Package
        run: bash openphd2.sh

      - name: Check Build Output
        run: ls /tmp/output/*phd2*

#      - name: Upload artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: packages
#          path : |
#            /tmp/output/indi-bin_*.deb
#            /tmp/output/libindi-dev_*.deb
#            /tmp/output/libindi-data_*.deb
#            /tmp/output/libindi1_*.deb
#            /tmp/output/phd2_*.deb
#            /tmp/output/indi-asi_*.deb
#            /tmp/output/libasi_*.deb

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/output/indi-bin_*.deb
            /tmp/output/libindi-dev_*.deb
            /tmp/output/libindi-data_*.deb
            /tmp/output/libindi1_*.deb
            /tmp/output/phd2_*.deb
            /tmp/output/indi-asi_*.deb
            /tmp/output/libasi_*.deb

