name: Build newest deb package for aarch64 debian

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    container:
      image: debian:trixie

    steps:
      - name: Get INDI Sources
        uses: actions/checkout@v3

      - name: Build Indi Debian Package
        run: bash indi.sh
      - name: Check Build Output
        run: ls /tmp/output/*indi*

      - name: Build indi-eqmod
        run: bash indi_3rdparty_indi-eqmod.sh
      - name: Check Build Output for indi-eqmod
        run: ls /tmp/output/*eqmod_*

      - name: Build libasi
        run: bash indi_3rdparty_libasi.sh
      - name: Check Build Output for libasi
        run: ls /tmp/output/libasi_*

      - name: Build indi-asi
        run: bash indi_3rdparty_indi-asi.sh
      - name: Check Build Output for indi-asi
        run: ls /tmp/output/*indi-asi_*

      - name: Build libqhy
        run: bash indi_3rdparty_libqhy.sh
      - name: Check Build Output for libqhy
        run: ls /tmp/output/libasi_*

      - name: Build indi-qhy
        run: bash indi_3rdparty_indi-qhy.sh
      - name: Check Build Output for indi-qhy
        run: ls /tmp/output/*indi-asi_*

      - name: Build fxload
        run: bash fxload.sh

#      - name: Build libatik
#        run: bash indi_3rdparty_libatik.sh
#      - name: Check Build Output for libatik
#        run: ls /tmp/output/libatik_*

#      - name: Build indi-atik
#        run: bash indi_3rdparty_indi-atik.sh
#      - name: Check Build Output for indi-atik
#        run: ls /tmp/output/*atik_*

      - name: Build Openphd2 Debian Package
        run: bash openphd2.sh
      - name: Check Build Output
        run: ls /tmp/output/*phd2*

#      - name: Upload artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: packages
#          path : |
#            /tmp/output/indi-bin_*.deb
#            /tmp/output/libindi-dev_*.deb
#            /tmp/output/libindi-data_*.deb
#            /tmp/output/libindi1_*.deb
#            /tmp/output/phd2_*.deb
#            /tmp/output/indi-asi_*.deb
#            /tmp/output/libasi_*.deb

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/output/indi-bin_*.deb
            /tmp/output/libindi-dev_*.deb
            /tmp/output/libindi-data_*.deb
            /tmp/output/libindi1_*.deb
            /tmp/output/phd2_*.deb
            /tmp/output/indi-asi_*.deb
            /tmp/output/libasi_*.deb
            /tmp/output/indi-eqmod_*.deb
            /tmp/output/libqhy_*.deb
            /tmp/output/indi-qhy_*.deb
            /tmp/output/fxload_*.deb
